[project]
name = 'artisan-marketplace'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.artisan-verification]
path = 'contracts/artisan-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.order-fulfillment]
path = 'contracts/order-fulfillment.clar'
clarity_version = 2
epoch = 2.5

[contracts.quality-assurance]
path = 'contracts/quality-assurance.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
